spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  redis:
    host: localhost
    password:
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttles:
            enable: true

  config:
    activate:
      on-profile: dev
    import:
      classpath:application-oauth2.yml

file:
  dir: src/test/resources/images
auth:
  secret: WTB1X2M0bnRfTDBva190aDFzX3NlY3IzdF9LM3lfUjFnaHQ/MTIzMjEwMTAxMTAxMjEyMTIxMzEzMTMxMzEzMQ==
  expiretime: 864000000

redirect:
  success: http://localhost:3000/
  fail: http://localhost:3000/fail

#logging:
#  level:
#    root: debug